[plugins]
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[versions]
# Paper API
paper = "1.21.1-R0.1-SNAPSHOT"
velocity = "3.3.0-SNAPSHOT"
minecraft = "1.21.1"
brigadier = "1.3.10"

# Vital API
vital-common = "0.0.6"
vital-paper = "1.0.6"

# Gradle Plugins
runPaper = "2.3.0"
minotaur = "2.8.7"
hangar = "0.1.2"
shadow = "8.3.0"

[libraries]
# Velocity API
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }

# Mojang API
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }

# Paper API
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version = "7.1.0-SNAPSHOT" }

# Vital API
vital-common = { module = "com.ryderbelserion.vital:common", version.ref = "vital-common" }
vital-paper = { module = "com.ryderbelserion.vital:paper", version.ref = "vital-paper" }